//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientVisit()
        {
            this.DetailPatientVisits = new HashSet<DetailPatientVisit>();
        }
    
        public int Id { get; set; }
        public string Anamnesis { get; set; }
        public string Implementation { get; set; }
        public string Notes { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPatientVisit> DetailPatientVisits { get; set; }
        public virtual MsPatient Patient { get; set; }
        public virtual MsDiagnose MsDiagnose { get; set; }
    }
}
